version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    depends_on:
    - dockdb

  dockdb:
    image: mysql
    container_name: db
    restart: always  #если контейнер упадет, он будет перезапущен
    ports:
      - "3333:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybdtest

  adminer:
    image: adminer   #полнофункциональный инструмент для управления базами данных
    restart: always
    ports:
      - "8080:8080"